# GENETARED BY NNDCT, DO NOT EDIT!

import torch
from torch import tensor
import pytorch_nndct as py_nndct

class TinyYoloV4(py_nndct.nn.NndctQuantModel):
    def __init__(self):
        super(TinyYoloV4, self).__init__()
        self.module_0 = py_nndct.nn.Input() #TinyYoloV4::input_0(TinyYoloV4::nndct_input_0)
        self.module_1 = py_nndct.nn.Conv2d(in_channels=3, out_channels=32, kernel_size=[3, 3], stride=[2, 2], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #TinyYoloV4::TinyYoloV4/CSPTiny[backbone]/Conv2dBatchLeaky[stage1]/Sequential[layers]/Conv2d[0]/ret.3(TinyYoloV4::nndct_conv2d_1)
        self.module_2 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #TinyYoloV4::TinyYoloV4/CSPTiny[backbone]/Conv2dBatchLeaky[stage1]/Sequential[layers]/LeakyReLU[2]/ret.7(TinyYoloV4::nndct_leaky_relu_2)
        self.module_3 = py_nndct.nn.Conv2d(in_channels=32, out_channels=64, kernel_size=[3, 3], stride=[2, 2], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #TinyYoloV4::TinyYoloV4/CSPTiny[backbone]/Conv2dBatchLeaky[stage2]/Sequential[layers]/Conv2d[0]/ret.9(TinyYoloV4::nndct_conv2d_3)
        self.module_4 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #TinyYoloV4::TinyYoloV4/CSPTiny[backbone]/Conv2dBatchLeaky[stage2]/Sequential[layers]/LeakyReLU[2]/ret.13(TinyYoloV4::nndct_leaky_relu_4)
        self.module_5 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #TinyYoloV4::TinyYoloV4/CSPTiny[backbone]/CSPBlock[stage3]/Conv2dBatchLeaky[conv1]/Sequential[layers]/Conv2d[0]/ret.15(TinyYoloV4::nndct_conv2d_5)
        self.module_6 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #TinyYoloV4::TinyYoloV4/CSPTiny[backbone]/CSPBlock[stage3]/Conv2dBatchLeaky[conv1]/Sequential[layers]/LeakyReLU[2]/ret.19(TinyYoloV4::nndct_leaky_relu_6)
        self.module_7 = py_nndct.nn.Conv2d(in_channels=64, out_channels=128, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #TinyYoloV4::TinyYoloV4/CSPTiny[backbone]/CSPBlock[stage3]/Conv2dBatchLeaky[conv2]/Sequential[layers]/Conv2d[0]/ret.21(TinyYoloV4::nndct_conv2d_7)
        self.module_8 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #TinyYoloV4::TinyYoloV4/CSPTiny[backbone]/CSPBlock[stage3]/Conv2dBatchLeaky[conv2]/Sequential[layers]/LeakyReLU[2]/ret.25(TinyYoloV4::nndct_leaky_relu_8)
        self.module_9 = py_nndct.nn.Conv2d(in_channels=128, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #TinyYoloV4::TinyYoloV4/CSPTiny[backbone]/CSPBlock[stage3]/Conv2dBatchLeaky[split0]/Sequential[layers]/Conv2d[0]/ret.27(TinyYoloV4::nndct_conv2d_9)
        self.module_10 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #TinyYoloV4::TinyYoloV4/CSPTiny[backbone]/CSPBlock[stage3]/Conv2dBatchLeaky[split0]/Sequential[layers]/LeakyReLU[2]/ret.31(TinyYoloV4::nndct_leaky_relu_10)
        self.module_11 = py_nndct.nn.Conv2d(in_channels=128, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #TinyYoloV4::TinyYoloV4/CSPTiny[backbone]/CSPBlock[stage3]/Conv2dBatchLeaky[split1]/Sequential[layers]/Conv2d[0]/ret.33(TinyYoloV4::nndct_conv2d_11)
        self.module_12 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #TinyYoloV4::TinyYoloV4/CSPTiny[backbone]/CSPBlock[stage3]/Conv2dBatchLeaky[split1]/Sequential[layers]/LeakyReLU[2]/ret.37(TinyYoloV4::nndct_leaky_relu_12)
        self.module_13 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #TinyYoloV4::TinyYoloV4/CSPTiny[backbone]/CSPBlock[stage3]/Conv2dBatchLeaky[conv3]/Sequential[layers]/Conv2d[0]/ret.39(TinyYoloV4::nndct_conv2d_13)
        self.module_14 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #TinyYoloV4::TinyYoloV4/CSPTiny[backbone]/CSPBlock[stage3]/Conv2dBatchLeaky[conv3]/Sequential[layers]/LeakyReLU[2]/ret.43(TinyYoloV4::nndct_leaky_relu_14)
        self.module_15 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #TinyYoloV4::TinyYoloV4/CSPTiny[backbone]/CSPBlock[stage3]/Conv2dBatchLeaky[conv4]/Sequential[layers]/Conv2d[0]/ret.45(TinyYoloV4::nndct_conv2d_15)
        self.module_16 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #TinyYoloV4::TinyYoloV4/CSPTiny[backbone]/CSPBlock[stage3]/Conv2dBatchLeaky[conv4]/Sequential[layers]/LeakyReLU[2]/ret.49(TinyYoloV4::nndct_leaky_relu_16)
        self.module_17 = py_nndct.nn.Add() #TinyYoloV4::TinyYoloV4/CSPTiny[backbone]/CSPBlock[stage3]/ret.51(TinyYoloV4::nndct_elemwise_add_17)
        self.module_18 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #TinyYoloV4::TinyYoloV4/CSPTiny[backbone]/CSPBlock[stage3]/Conv2dBatchLeaky[conv5]/Sequential[layers]/Conv2d[0]/ret.53(TinyYoloV4::nndct_conv2d_18)
        self.module_19 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #TinyYoloV4::TinyYoloV4/CSPTiny[backbone]/CSPBlock[stage3]/Conv2dBatchLeaky[conv5]/Sequential[layers]/LeakyReLU[2]/ret.57(TinyYoloV4::nndct_leaky_relu_19)
        self.module_20 = py_nndct.nn.Cat() #TinyYoloV4::TinyYoloV4/CSPTiny[backbone]/CSPBlock[stage3]/ret.59(TinyYoloV4::nndct_concat_20)
        self.module_21 = py_nndct.nn.MaxPool2d(kernel_size=[2, 2], stride=[2, 2], padding=[0, 0], dilation=[1, 1], ceil_mode=False) #TinyYoloV4::TinyYoloV4/CSPTiny[backbone]/MaxPool2d[pool1]/8420(TinyYoloV4::nndct_maxpool_21)
        self.module_22 = py_nndct.nn.Conv2d(in_channels=128, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #TinyYoloV4::TinyYoloV4/CSPTiny[backbone]/CSPBlock[stage4]/Conv2dBatchLeaky[conv1]/Sequential[layers]/Conv2d[0]/ret.61(TinyYoloV4::nndct_conv2d_22)
        self.module_23 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #TinyYoloV4::TinyYoloV4/CSPTiny[backbone]/CSPBlock[stage4]/Conv2dBatchLeaky[conv1]/Sequential[layers]/LeakyReLU[2]/ret.65(TinyYoloV4::nndct_leaky_relu_23)
        self.module_24 = py_nndct.nn.Conv2d(in_channels=128, out_channels=256, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #TinyYoloV4::TinyYoloV4/CSPTiny[backbone]/CSPBlock[stage4]/Conv2dBatchLeaky[conv2]/Sequential[layers]/Conv2d[0]/ret.67(TinyYoloV4::nndct_conv2d_24)
        self.module_25 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #TinyYoloV4::TinyYoloV4/CSPTiny[backbone]/CSPBlock[stage4]/Conv2dBatchLeaky[conv2]/Sequential[layers]/LeakyReLU[2]/ret.71(TinyYoloV4::nndct_leaky_relu_25)
        self.module_26 = py_nndct.nn.Conv2d(in_channels=256, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #TinyYoloV4::TinyYoloV4/CSPTiny[backbone]/CSPBlock[stage4]/Conv2dBatchLeaky[split0]/Sequential[layers]/Conv2d[0]/ret.73(TinyYoloV4::nndct_conv2d_26)
        self.module_27 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #TinyYoloV4::TinyYoloV4/CSPTiny[backbone]/CSPBlock[stage4]/Conv2dBatchLeaky[split0]/Sequential[layers]/LeakyReLU[2]/ret.77(TinyYoloV4::nndct_leaky_relu_27)
        self.module_28 = py_nndct.nn.Conv2d(in_channels=256, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #TinyYoloV4::TinyYoloV4/CSPTiny[backbone]/CSPBlock[stage4]/Conv2dBatchLeaky[split1]/Sequential[layers]/Conv2d[0]/ret.79(TinyYoloV4::nndct_conv2d_28)
        self.module_29 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #TinyYoloV4::TinyYoloV4/CSPTiny[backbone]/CSPBlock[stage4]/Conv2dBatchLeaky[split1]/Sequential[layers]/LeakyReLU[2]/ret.83(TinyYoloV4::nndct_leaky_relu_29)
        self.module_30 = py_nndct.nn.Conv2d(in_channels=128, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #TinyYoloV4::TinyYoloV4/CSPTiny[backbone]/CSPBlock[stage4]/Conv2dBatchLeaky[conv3]/Sequential[layers]/Conv2d[0]/ret.85(TinyYoloV4::nndct_conv2d_30)
        self.module_31 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #TinyYoloV4::TinyYoloV4/CSPTiny[backbone]/CSPBlock[stage4]/Conv2dBatchLeaky[conv3]/Sequential[layers]/LeakyReLU[2]/ret.89(TinyYoloV4::nndct_leaky_relu_31)
        self.module_32 = py_nndct.nn.Conv2d(in_channels=128, out_channels=128, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #TinyYoloV4::TinyYoloV4/CSPTiny[backbone]/CSPBlock[stage4]/Conv2dBatchLeaky[conv4]/Sequential[layers]/Conv2d[0]/ret.91(TinyYoloV4::nndct_conv2d_32)
        self.module_33 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #TinyYoloV4::TinyYoloV4/CSPTiny[backbone]/CSPBlock[stage4]/Conv2dBatchLeaky[conv4]/Sequential[layers]/LeakyReLU[2]/ret.95(TinyYoloV4::nndct_leaky_relu_33)
        self.module_34 = py_nndct.nn.Add() #TinyYoloV4::TinyYoloV4/CSPTiny[backbone]/CSPBlock[stage4]/ret.97(TinyYoloV4::nndct_elemwise_add_34)
        self.module_35 = py_nndct.nn.Conv2d(in_channels=128, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #TinyYoloV4::TinyYoloV4/CSPTiny[backbone]/CSPBlock[stage4]/Conv2dBatchLeaky[conv5]/Sequential[layers]/Conv2d[0]/ret.99(TinyYoloV4::nndct_conv2d_35)
        self.module_36 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #TinyYoloV4::TinyYoloV4/CSPTiny[backbone]/CSPBlock[stage4]/Conv2dBatchLeaky[conv5]/Sequential[layers]/LeakyReLU[2]/ret.103(TinyYoloV4::nndct_leaky_relu_36)
        self.module_37 = py_nndct.nn.Cat() #TinyYoloV4::TinyYoloV4/CSPTiny[backbone]/CSPBlock[stage4]/ret.105(TinyYoloV4::nndct_concat_37)
        self.module_38 = py_nndct.nn.MaxPool2d(kernel_size=[2, 2], stride=[2, 2], padding=[0, 0], dilation=[1, 1], ceil_mode=False) #TinyYoloV4::TinyYoloV4/CSPTiny[backbone]/MaxPool2d[pool2]/8653(TinyYoloV4::nndct_maxpool_38)
        self.module_39 = py_nndct.nn.Conv2d(in_channels=256, out_channels=256, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #TinyYoloV4::TinyYoloV4/CSPTiny[backbone]/CSPBlock[stage5]/Conv2dBatchLeaky[conv1]/Sequential[layers]/Conv2d[0]/ret.107(TinyYoloV4::nndct_conv2d_39)
        self.module_40 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #TinyYoloV4::TinyYoloV4/CSPTiny[backbone]/CSPBlock[stage5]/Conv2dBatchLeaky[conv1]/Sequential[layers]/LeakyReLU[2]/ret.111(TinyYoloV4::nndct_leaky_relu_40)
        self.module_41 = py_nndct.nn.Conv2d(in_channels=256, out_channels=512, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #TinyYoloV4::TinyYoloV4/CSPTiny[backbone]/CSPBlock[stage5]/Conv2dBatchLeaky[conv2]/Sequential[layers]/Conv2d[0]/ret.113(TinyYoloV4::nndct_conv2d_41)
        self.module_42 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #TinyYoloV4::TinyYoloV4/CSPTiny[backbone]/CSPBlock[stage5]/Conv2dBatchLeaky[conv2]/Sequential[layers]/LeakyReLU[2]/ret.117(TinyYoloV4::nndct_leaky_relu_42)
        self.module_43 = py_nndct.nn.Conv2d(in_channels=512, out_channels=256, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #TinyYoloV4::TinyYoloV4/CSPTiny[backbone]/CSPBlock[stage5]/Conv2dBatchLeaky[split0]/Sequential[layers]/Conv2d[0]/ret.119(TinyYoloV4::nndct_conv2d_43)
        self.module_44 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #TinyYoloV4::TinyYoloV4/CSPTiny[backbone]/CSPBlock[stage5]/Conv2dBatchLeaky[split0]/Sequential[layers]/LeakyReLU[2]/ret.123(TinyYoloV4::nndct_leaky_relu_44)
        self.module_45 = py_nndct.nn.Conv2d(in_channels=512, out_channels=256, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #TinyYoloV4::TinyYoloV4/CSPTiny[backbone]/CSPBlock[stage5]/Conv2dBatchLeaky[split1]/Sequential[layers]/Conv2d[0]/ret.125(TinyYoloV4::nndct_conv2d_45)
        self.module_46 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #TinyYoloV4::TinyYoloV4/CSPTiny[backbone]/CSPBlock[stage5]/Conv2dBatchLeaky[split1]/Sequential[layers]/LeakyReLU[2]/ret.129(TinyYoloV4::nndct_leaky_relu_46)
        self.module_47 = py_nndct.nn.Conv2d(in_channels=256, out_channels=256, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #TinyYoloV4::TinyYoloV4/CSPTiny[backbone]/CSPBlock[stage5]/Conv2dBatchLeaky[conv3]/Sequential[layers]/Conv2d[0]/ret.131(TinyYoloV4::nndct_conv2d_47)
        self.module_48 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #TinyYoloV4::TinyYoloV4/CSPTiny[backbone]/CSPBlock[stage5]/Conv2dBatchLeaky[conv3]/Sequential[layers]/LeakyReLU[2]/ret.135(TinyYoloV4::nndct_leaky_relu_48)
        self.module_49 = py_nndct.nn.Conv2d(in_channels=256, out_channels=256, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #TinyYoloV4::TinyYoloV4/CSPTiny[backbone]/CSPBlock[stage5]/Conv2dBatchLeaky[conv4]/Sequential[layers]/Conv2d[0]/ret.137(TinyYoloV4::nndct_conv2d_49)
        self.module_50 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #TinyYoloV4::TinyYoloV4/CSPTiny[backbone]/CSPBlock[stage5]/Conv2dBatchLeaky[conv4]/Sequential[layers]/LeakyReLU[2]/ret.141(TinyYoloV4::nndct_leaky_relu_50)
        self.module_51 = py_nndct.nn.Add() #TinyYoloV4::TinyYoloV4/CSPTiny[backbone]/CSPBlock[stage5]/ret.143(TinyYoloV4::nndct_elemwise_add_51)
        self.module_52 = py_nndct.nn.Conv2d(in_channels=256, out_channels=256, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #TinyYoloV4::TinyYoloV4/CSPTiny[backbone]/CSPBlock[stage5]/Conv2dBatchLeaky[conv5]/Sequential[layers]/Conv2d[0]/ret.145(TinyYoloV4::nndct_conv2d_52)
        self.module_53 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #TinyYoloV4::TinyYoloV4/CSPTiny[backbone]/CSPBlock[stage5]/Conv2dBatchLeaky[conv5]/Sequential[layers]/LeakyReLU[2]/ret.149(TinyYoloV4::nndct_leaky_relu_53)
        self.module_54 = py_nndct.nn.Cat() #TinyYoloV4::TinyYoloV4/CSPTiny[backbone]/CSPBlock[stage5]/ret.151(TinyYoloV4::nndct_concat_54)
        self.module_55 = py_nndct.nn.MaxPool2d(kernel_size=[2, 2], stride=[2, 2], padding=[0, 0], dilation=[1, 1], ceil_mode=False) #TinyYoloV4::TinyYoloV4/CSPTiny[backbone]/MaxPool2d[pool3]/8886(TinyYoloV4::nndct_maxpool_55)
        self.module_56 = py_nndct.nn.Conv2d(in_channels=512, out_channels=512, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #TinyYoloV4::TinyYoloV4/CSPTiny[backbone]/Conv2dBatchLeaky[stage6]/Sequential[layers]/Conv2d[0]/ret.153(TinyYoloV4::nndct_conv2d_56)
        self.module_57 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #TinyYoloV4::TinyYoloV4/CSPTiny[backbone]/Conv2dBatchLeaky[stage6]/Sequential[layers]/LeakyReLU[2]/ret.157(TinyYoloV4::nndct_leaky_relu_57)
        self.module_58 = py_nndct.nn.Conv2d(in_channels=512, out_channels=256, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #TinyYoloV4::TinyYoloV4/Neck[neck]/Conv2dBatchLeaky[first_block1]/Sequential[layers]/Conv2d[0]/ret.159(TinyYoloV4::nndct_conv2d_58)
        self.module_59 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #TinyYoloV4::TinyYoloV4/Neck[neck]/Conv2dBatchLeaky[first_block1]/Sequential[layers]/LeakyReLU[2]/ret.163(TinyYoloV4::nndct_leaky_relu_59)
        self.module_60 = py_nndct.nn.Conv2d(in_channels=256, out_channels=512, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #TinyYoloV4::TinyYoloV4/Neck[neck]/Conv2dBatchLeaky[first_block2]/Sequential[layers]/Conv2d[0]/ret.165(TinyYoloV4::nndct_conv2d_60)
        self.module_61 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #TinyYoloV4::TinyYoloV4/Neck[neck]/Conv2dBatchLeaky[first_block2]/Sequential[layers]/LeakyReLU[2]/ret.169(TinyYoloV4::nndct_leaky_relu_61)
        self.module_62 = py_nndct.nn.Conv2d(in_channels=512, out_channels=512, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #TinyYoloV4::TinyYoloV4/Neck[neck]/Conv2dBatchLeaky[pointconv1]/Sequential[layers]/Conv2d[0]/ret.171(TinyYoloV4::nndct_conv2d_62)
        self.module_63 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #TinyYoloV4::TinyYoloV4/Neck[neck]/Conv2dBatchLeaky[pointconv1]/Sequential[layers]/LeakyReLU[2]/ret.175(TinyYoloV4::nndct_leaky_relu_63)
        self.module_64 = py_nndct.nn.Conv2d(in_channels=512, out_channels=256, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #TinyYoloV4::TinyYoloV4/Neck[neck]/Conv2dBatchLeaky[sec_block1]/Sequential[layers]/Conv2d[0]/ret.177(TinyYoloV4::nndct_conv2d_64)
        self.module_65 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #TinyYoloV4::TinyYoloV4/Neck[neck]/Conv2dBatchLeaky[sec_block1]/Sequential[layers]/LeakyReLU[2]/ret.181(TinyYoloV4::nndct_leaky_relu_65)
        self.module_66 = py_nndct.nn.Interpolate() #TinyYoloV4::TinyYoloV4/Neck[neck]/Upsample[upsample]/ret.183(TinyYoloV4::nndct_resize_66)
        self.module_67 = py_nndct.nn.Cat() #TinyYoloV4::TinyYoloV4/Neck[neck]/ret.185(TinyYoloV4::nndct_concat_67)
        self.module_68 = py_nndct.nn.Conv2d(in_channels=512, out_channels=256, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #TinyYoloV4::TinyYoloV4/Neck[neck]/Conv2dBatchLeaky[sec_block2]/Sequential[layers]/Conv2d[0]/ret.187(TinyYoloV4::nndct_conv2d_68)
        self.module_69 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #TinyYoloV4::TinyYoloV4/Neck[neck]/Conv2dBatchLeaky[sec_block2]/Sequential[layers]/LeakyReLU[2]/ret.191(TinyYoloV4::nndct_leaky_relu_69)
        self.module_70 = py_nndct.nn.Conv2d(in_channels=256, out_channels=256, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #TinyYoloV4::TinyYoloV4/Neck[neck]/Conv2dBatchLeaky[pointconv2]/Sequential[layers]/Conv2d[0]/ret.193(TinyYoloV4::nndct_conv2d_70)
        self.module_71 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #TinyYoloV4::TinyYoloV4/Neck[neck]/Conv2dBatchLeaky[pointconv2]/Sequential[layers]/LeakyReLU[2]/ret.197(TinyYoloV4::nndct_leaky_relu_71)
        self.module_72 = py_nndct.nn.Conv2d(in_channels=512, out_channels=1024, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #TinyYoloV4::TinyYoloV4/Head[head]/Sequential[out1]/Conv2dBatchLeaky[0]/Sequential[layers]/Conv2d[0]/ret.199(TinyYoloV4::nndct_conv2d_72)
        self.module_73 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #TinyYoloV4::TinyYoloV4/Head[head]/Sequential[out1]/Conv2dBatchLeaky[0]/Sequential[layers]/LeakyReLU[2]/ret.203(TinyYoloV4::nndct_leaky_relu_73)
        self.module_74 = py_nndct.nn.Conv2d(in_channels=1024, out_channels=18, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #TinyYoloV4::TinyYoloV4/Head[head]/Sequential[out1]/Conv2dBatchLeaky[1]/Sequential[layers]/Conv2d[0]/ret.205(TinyYoloV4::nndct_conv2d_74)
        self.module_75 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #TinyYoloV4::TinyYoloV4/Head[head]/Sequential[out1]/Conv2dBatchLeaky[1]/Sequential[layers]/LeakyReLU[2]/ret.209(TinyYoloV4::nndct_leaky_relu_75)
        self.module_76 = py_nndct.nn.Conv2d(in_channels=256, out_channels=512, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #TinyYoloV4::TinyYoloV4/Head[head]/Sequential[out2]/Conv2dBatchLeaky[0]/Sequential[layers]/Conv2d[0]/ret.211(TinyYoloV4::nndct_conv2d_76)
        self.module_77 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #TinyYoloV4::TinyYoloV4/Head[head]/Sequential[out2]/Conv2dBatchLeaky[0]/Sequential[layers]/LeakyReLU[2]/ret.215(TinyYoloV4::nndct_leaky_relu_77)
        self.module_78 = py_nndct.nn.Conv2d(in_channels=512, out_channels=18, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #TinyYoloV4::TinyYoloV4/Head[head]/Sequential[out2]/Conv2dBatchLeaky[1]/Sequential[layers]/Conv2d[0]/ret.217(TinyYoloV4::nndct_conv2d_78)
        self.module_79 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #TinyYoloV4::TinyYoloV4/Head[head]/Sequential[out2]/Conv2dBatchLeaky[1]/Sequential[layers]/LeakyReLU[2]/ret.221(TinyYoloV4::nndct_leaky_relu_79)
        self.module_80 = py_nndct.nn.Module('nndct_permute') #TinyYoloV4::TinyYoloV4/ret.223(TinyYoloV4::nndct_permute_80)
        self.module_81 = py_nndct.nn.Module('nndct_permute') #TinyYoloV4::TinyYoloV4/ret.225(TinyYoloV4::nndct_permute_81)
        self.module_82 = py_nndct.nn.Module('nndct_shape') #TinyYoloV4::TinyYoloV4/9252(TinyYoloV4::nndct_shape_82)
        self.module_83 = py_nndct.nn.Module('nndct_shape') #TinyYoloV4::TinyYoloV4/9257(TinyYoloV4::nndct_shape_83)
        self.module_84 = py_nndct.nn.Module('nndct_shape') #TinyYoloV4::TinyYoloV4/9262(TinyYoloV4::nndct_shape_84)
        self.module_85 = py_nndct.nn.Module('nndct_reshape') #TinyYoloV4::TinyYoloV4/ret.233(TinyYoloV4::nndct_reshape_85)
        self.module_86 = py_nndct.nn.Module('nndct_shape') #TinyYoloV4::TinyYoloV4/9272(TinyYoloV4::nndct_shape_86)
        self.module_87 = py_nndct.nn.Module('nndct_shape') #TinyYoloV4::TinyYoloV4/9277(TinyYoloV4::nndct_shape_87)
        self.module_88 = py_nndct.nn.Module('nndct_shape') #TinyYoloV4::TinyYoloV4/9282(TinyYoloV4::nndct_shape_88)
        self.module_89 = py_nndct.nn.Module('nndct_reshape') #TinyYoloV4::TinyYoloV4/ret(TinyYoloV4::nndct_reshape_89)

    @py_nndct.nn.forward_processor
    def forward(self, *args):
        output_module_0 = self.module_0(input=args[0])
        output_module_0 = self.module_1(output_module_0)
        output_module_0 = self.module_2(output_module_0)
        output_module_0 = self.module_3(output_module_0)
        output_module_0 = self.module_4(output_module_0)
        output_module_0 = self.module_5(output_module_0)
        output_module_0 = self.module_6(output_module_0)
        output_module_0 = self.module_7(output_module_0)
        output_module_0 = self.module_8(output_module_0)
        output_module_9 = self.module_9(output_module_0)
        output_module_9 = self.module_10(output_module_9)
        output_module_11 = self.module_11(output_module_0)
        output_module_11 = self.module_12(output_module_11)
        output_module_13 = self.module_13(output_module_11)
        output_module_13 = self.module_14(output_module_13)
        output_module_13 = self.module_15(output_module_13)
        output_module_13 = self.module_16(output_module_13)
        output_module_17 = self.module_17(input=output_module_11, other=output_module_13, alpha=1)
        output_module_17 = self.module_18(output_module_17)
        output_module_17 = self.module_19(output_module_17)
        output_module_9 = self.module_20(dim=1, tensors=[output_module_9,output_module_17])
        output_module_9 = self.module_21(output_module_9)
        output_module_9 = self.module_22(output_module_9)
        output_module_9 = self.module_23(output_module_9)
        output_module_9 = self.module_24(output_module_9)
        output_module_9 = self.module_25(output_module_9)
        output_module_26 = self.module_26(output_module_9)
        output_module_26 = self.module_27(output_module_26)
        output_module_28 = self.module_28(output_module_9)
        output_module_28 = self.module_29(output_module_28)
        output_module_30 = self.module_30(output_module_28)
        output_module_30 = self.module_31(output_module_30)
        output_module_30 = self.module_32(output_module_30)
        output_module_30 = self.module_33(output_module_30)
        output_module_34 = self.module_34(input=output_module_28, other=output_module_30, alpha=1)
        output_module_34 = self.module_35(output_module_34)
        output_module_34 = self.module_36(output_module_34)
        output_module_26 = self.module_37(dim=1, tensors=[output_module_26,output_module_34])
        output_module_26 = self.module_38(output_module_26)
        output_module_26 = self.module_39(output_module_26)
        output_module_26 = self.module_40(output_module_26)
        output_module_26 = self.module_41(output_module_26)
        output_module_26 = self.module_42(output_module_26)
        output_module_43 = self.module_43(output_module_26)
        output_module_43 = self.module_44(output_module_43)
        output_module_45 = self.module_45(output_module_26)
        output_module_45 = self.module_46(output_module_45)
        output_module_47 = self.module_47(output_module_45)
        output_module_47 = self.module_48(output_module_47)
        output_module_47 = self.module_49(output_module_47)
        output_module_47 = self.module_50(output_module_47)
        output_module_51 = self.module_51(input=output_module_45, other=output_module_47, alpha=1)
        output_module_51 = self.module_52(output_module_51)
        output_module_51 = self.module_53(output_module_51)
        output_module_43 = self.module_54(dim=1, tensors=[output_module_43,output_module_51])
        output_module_55 = self.module_55(output_module_43)
        output_module_55 = self.module_56(output_module_55)
        output_module_55 = self.module_57(output_module_55)
        output_module_55 = self.module_58(output_module_55)
        output_module_55 = self.module_59(output_module_55)
        output_module_60 = self.module_60(output_module_55)
        output_module_60 = self.module_61(output_module_60)
        output_module_60 = self.module_62(output_module_60)
        output_module_60 = self.module_63(output_module_60)
        output_module_64 = self.module_64(output_module_43)
        output_module_64 = self.module_65(output_module_64)
        output_module_66 = self.module_66(input=output_module_55, size=None, scale_factor=[2.0,2.0], mode='nearest')
        output_module_64 = self.module_67(dim=1, tensors=[output_module_64,output_module_66])
        output_module_64 = self.module_68(output_module_64)
        output_module_64 = self.module_69(output_module_64)
        output_module_64 = self.module_70(output_module_64)
        output_module_64 = self.module_71(output_module_64)
        output_module_60 = self.module_72(output_module_60)
        output_module_60 = self.module_73(output_module_60)
        output_module_60 = self.module_74(output_module_60)
        output_module_60 = self.module_75(output_module_60)
        output_module_64 = self.module_76(output_module_64)
        output_module_64 = self.module_77(output_module_64)
        output_module_64 = self.module_78(output_module_64)
        output_module_64 = self.module_79(output_module_64)
        output_module_60 = self.module_80(dims=[0,2,3,1], input=output_module_60)
        output_module_64 = self.module_81(dims=[0,2,3,1], input=output_module_64)
        output_module_82 = self.module_82(input=output_module_60, dim=0)
        output_module_83 = self.module_83(input=output_module_60, dim=1)
        output_module_84 = self.module_84(input=output_module_60, dim=2)
        output_module_85 = self.module_85(input=output_module_60, shape=[output_module_82,output_module_83,output_module_84,3,6])
        output_module_86 = self.module_86(input=output_module_64, dim=0)
        output_module_87 = self.module_87(input=output_module_64, dim=1)
        output_module_88 = self.module_88(input=output_module_64, dim=2)
        output_module_89 = self.module_89(input=output_module_64, shape=[output_module_86,output_module_87,output_module_88,3,6])
        return (output_module_85,output_module_89)
